### ISSUE TITLE
album creation is broken - 1 album per photo

### ISSUE THREAD

**Issue by norbusan** [nmrshll/gphotos-uploader-cli#19]
I tried to upload a bunch of photos and did set album
```
      makeAlbums: {
        enabled: true
        use: folderNames
      }
```
which resulted in one album per *photo* instead of per folder. This is with an installation as of today (2018-10-22) direct from Github with go, running Debian/sid.

**Comment by occamshatchet** [comment]
I have seen the same thing on MAC OS 10.14.1. It inconsistently works; sometimes it will add all photos to a single album, others it will add half the photos to a album and the rest will create a new album with one photo in it. Other times it will only create a new album with one photo in it.

**Comment by antonmos** [comment]
Same on Ubuntu 18.10

**Comment by antonmos** [comment]
I suspect this is due to the [list albums call](https://github.com/nmrshll/google-photos-api-client-go/blob/master/lib-gphotos/client.go#L131) returning paginated results per this comment https://github.com/googleapis/google-api-go-client/blob/master/photoslibrary/v1/photoslibrary-gen.go#L2393

my guess is that it might be better to use MediaItemService.Search to search for existing albums instead of paginating through the list (which is likely to be too slow).  See https://github.com/googleapis/google-api-go-client/blob/master/photoslibrary/v1/photoslibrary-gen.go#L2881

I dont really know any go otherwise i'd definitely PR this.

**Comment by driv** [comment]
@antonmos it looks like you're right, it works fine on new pictures (albums first on the list) but it starts creating multiple albums for old pictures.

**Comment by driv** [comment]
Anyway, it should probably store the album info locally after creating it and re use it instead of listing for every picture. At least per directory.

**Comment by adkfan** [comment]
Just started working with this tool and am running into the same problem.  Not a go programmer, but happy to help out with testing if needed.  Thrilled to see a linux compatible batch uploader with the new API!

**Comment by tonymet** [comment]
I've addressed the album issue here -- it will only create one album per directory. Could I ask your help in testing the branch? @adkfan 

https://github.com/nmrshll/gphotos-uploader-cli/pull/45

**Comment by adkfan** [comment]
Yes, absolutely!  One catch....I'm completely new to GitHub.  How do I sync your branch with the fix in it to my local machine for testing?

**Comment by norbusan** [comment]
@tonymet Thanks, with the PR it works, both with album creation enabled and disabled! Thanks.

**Comment by ryanov** [comment]
Happy to test as well. I'm seeing the same "one photo per album" problem with the existing release.

**Comment by jrywu** [comment]
@tonymet Thanks for the PR.  In my test, it only solve partial of the issue.  
If the number of albums is large (larger than 20), the PR will recreate empty albums corresponding to folders with files all marked as uploaded.
I tried to move the get or create album code block after IsAlreadyUploaded check and right before the FileUpload job creation and only doing once after entering a new folder.   The modification does not create empty albums, but still recreate a duplicated album corresponding to last discontinued folder with files not uploaded.
I tried to trace the code, and found the root cause is at client.AlbumByname() in GetOrCreateAlbumByName() function.  The list of albums inside client.AlbumByName() only return first 20 items.  This actually confirmed the suspect of @antonmos.  The issue is from the paginated results of google API design. The list albums call only return first page with default page size of 20.

**Comment by tonymet** [comment]
@jrywu big help thanks for the feedback i'll see if I can repro and correct the fault. 

If you could create a throwaway with > 20 albums and share the creds with me, that would help me repro and fix.

**Comment by jrywu** [comment]
@tonymet , you are welcome.
There are possibily two solutions.
Solution 1: From google photos API documentation, the album Id is "persistent for sessions".  Since we only need album id when upload photos.  We can store the album id upon created in leveldb like what we did for marking photos to be uploaded in leveldb.  Instead of store mtime+hash for uploaded files, we can store the album id for folders.  This should be a easy fix and  most efficient to store everything local for reducing API calls.  In your PR, the local stored album should be replaced with albumId instead.
Solution 2: To fix the pagination bug in AlbumByName of client.go.   This modification should be PR in the under-layer google-photos-api-client-go instead here.
Here is a quick fix to do pagination when next page token is available ( means album numbers > page size). 
I am new to golang and this is a dirty implementation without consider errors or duplicated album names, but it works for me.
func (client *Client) AlbumByName(name string) (album *photoslibrary.Album, found bool, err error) {

	ctx := context.Background()
	c := client.Albums.List().Context(ctx)
	listAlbumsResponse, err := c.Do()
	if err != nil {
		return nil, false, stacktrace.Propagate(err, "failed listing albums")
	}

	if listAlbumsResponse.NextPageToken != "" {
		var albumFound *photoslibrary.Album
		albumFound = nil
		walkPages := func(listAlbumsResponse *photoslibrary.ListAlbumsResponse) error {
			for _, album := range listAlbumsResponse.Albums {
				log.Printf("Matching album title: %s to %s", album.Title, name)
				if album.Title == name {
					albumFound = album
					log.Printf("Matched album %s found with id: %s", album.Title, album.Id)
				}
			}
			return nil
		}
		c.Pages(ctx, walkPages)
		if albumFound != nil {
			return albumFound, true, nil
		} else {
			return nil, false, nil
		}
	} else {

		for _, album := range listAlbumsResponse.Albums {
			if album.Title == name {
				return album, true, nil
			}
		}
	}
	return nil, false, nil
}

**Comment by thefrip** [comment]
I didn't see the above fix and did my own, quite similar. Here it is (modification to AlbumByName in client.go, including optimisation by fetching the maximum number of album names in one go, ie 50):

	func (client *Client) AlbumByName(name string) (album *photoslibrary.Album, found bool, err error) {
	nextToken := ""
	for {

		listAlbumsResponse, err := client.Albums.List().PageSize(50).PageToken(nextToken).Do()
		if err != nil {
			 return nil, false, stacktrace.Propagate(err, "failed listing albums")
		}
		for _, album := range listAlbumsResponse.Albums {
			if album.Title == name {
				return album, true, nil
			}
		}
		nextToken = listAlbumsResponse.NextPageToken
		if nextToken == "" {
			break
		}
	}
	return nil, false, nil
	}

**Comment by pacoorozco** [comment]
I think that albums id should be cached (as mentioned previously).

**Comment by pacoorozco** [comment]
Hi,

**I've been testing albums creation and it works fine**. This is the way I've tested it. 

1. I've created a Folder with more than 50 folders inside. 
2. There is an image inside each folder.
3. I've called `gphotos-uploader-cli` to upload the Folder. 

The result is having the Folder and the inside folders created. So it seems to be working fine.

**Can you explain how to reproduce the error?**

**Comment by dotanalon** [comment]
in my case the issue is that on each of the folders there is multiple images, and 5 albums created under the same name, on the first 4 albums there is only one picture (different), and in the last album there is the rest of the folder containing

**Comment by pacoorozco** [comment]
Hi @dotanalon 

I've found the problem... This CLI works file by file spawning several threads to do uploads.

But `GetOrCreateAlbumByName()` is inside these threads and the function is not thread safe. **Good catch**

Now I'm thinking how to solve it. The best approach would be put `GetOrCreateAlbumByName()` out of the thread, maintaining the upload file process only inside.

**Comment by antonmos** [comment]
@pacoorozco did you see my comment about pagination https://github.com/gphotosuploader/gphotos-uploader-cli/issues/19#issuecomment-450782703 ?

**Comment by pacoorozco** [comment]
@antonmos Yes I've seen it. **Current `master` branch has a fix for albums pagination**, but this doesn't address the problem with album creation... 

There are several concurrent processes calling `GetOrCreateAlbumByName()`. It's happening that when one process is creating the album, another process doesn't know about it, so it will try to create it again. Due to the possibility of creating several albums with the same name, different `upload()` process are using different albums IDs. You can see it [here](https://github.com/gphotosuploader/gphotos-uploader-cli/blob/3fe52487b43ac2d4b67c4eb531dae4356cb1dbdb/upload/fileUpload.go#L76).

This bug was probably introduced when [concurrency was implemented](https://github.com/gphotosuploader/gphotos-uploader-cli/commit/e58057a3d6f32b7e37d37d6b1c059cee631ceddd#diff-62ec878e0d5cfa576428c0c6862adbca). Previous of that the album pagination was causing some issues, too. :cry:

**Comment by pacoorozco** [comment]
Hi @dotanalon and @antonmos 

Can you test source code on branch `issue-19` or if you prefer use binaries for [v0.8.1-pre](https://github.com/gphotosuploader/gphotos-uploader-cli/releases/tag/v0.8.1-pre). 

It should fix the problem... right?

**Comment by dotanalon** [comment]
I will test it in few hours and update..
Thanks,

**Comment by pacoorozco** [comment]
@dotanalon were you be able to test it?

**Comment by dotanalon** [comment]
Not yet...
Sorry, will try to do so tomorrow
Thanks,

**Comment by antonmos** [comment]
i tested it and problems persist. 
When i uploaded to an account that had 17 albums it was working fine. New album got created and all the pics went into it.
When I uploaded to an account that had about 190 albums, duplicate albums got created and pictures got split up between them.
Let me know what other info i can provide to help!

**Comment by pacoorozco** [comment]
@antonmos It's very strange, because the number of albums will not affect how the code is creating it. When you are referring to *When I uploaded to an account that had about 17 / 190 albums*, It look like you are referring ti the amount of albums that already exists.

Bear in mind, that `gphotos-uploader-cli` is only able to upload files to albums that has been created by `gphotos-uploader-cli`. If you are trying to upload pictures to existent albums (created outside this CLI) you are going to end up with a new album with the same name. 

**Are you trying to upload to existent albums?** Existent means not created by `gphotos-uploader-cli`.

Thanks for taking time to get more information in order to solve the issue.

**Comment by antonmos** [comment]
no, that duplicated album was not already there.
However, I think when i just started uploading the upload stopped due to running into .DS_Store file.  I had to add that to exludedPatterns and restart it.
Is it possible that the db did not get updated with the reference to the album that got created?

**Comment by pacoorozco** [comment]
@antonmos We are not keeping album's information locally. So It doesn't matter if you retry without cleaning local DB. 

So you have a collection of 190 albums that are not already created in Google Photos (or it were created by `gphotos-uploader-cli`). Then, when you run the `google-photos-cli` (using [v0.8.1-pre](https://github.com/gphotosuploader/gphotos-uploader-cli/releases/tag/v0.8.1-pre))  to upload more pictures, you see new albums are created with duplicated names, right?

**Comment by antonmos** [comment]
> So you have a collection of 190 albums that are not already created in Google Photos (or it were created by gphotos-uploader-cli). Then, when you run the google-photos-cli (using v0.8.1-pre) to upload more pictures, you see new albums are created with duplicated names, right?
Yes, but it my case it was interrupted.

> Bear in mind, that gphotos-uploader-cli is only able to upload files to albums that has been created by gphotos-uploader-cli. If you are trying to upload pictures to existent albums (created outside this CLI) you are going to end up with a new album with the same name.

Per above, if you are not keeping track of albums locally, then wouldn't restarting the upload after interrupting due to .DS_Store, result in the duplication?

**Comment by antonmos** [comment]
Just so i understand, if you are not keeping track of albums locally, how come `photos-uploader-cli is only able to upload files to albums that has been created by gphotos-uploader-cli`?

**Comment by pacoorozco** [comment]
It gets album's list from Google Photos by folder's name

**Comment by antonmos** [comment]
I tested it again and was able to reproduce it without interrupting the
upload.
Btw, I am uploading a folder which contains 10+ other folders, which
actually contain the photos.

**Comment by mjhatcher** [comment]
As far as I see the issue seems to relate to the concurrency logic. I have tested with a completely empty photos account - no existing photos, no existing albums. With the default settings and the latest source from master I am able to replicate duplicate albums immediately:

The first three photos being uploaded are all in the same folder. They ended up in 3 separate folders each with the same name. Next 2 are from the next folder; again they end up in duplicates.

I changed `const maxNumberOfWorkers = 1` and retested as suggested by @pacoorozco above and results are as expected - no duplicates.

I am now testing with the **issue-19** branch. Same configuration and same photos but back to the default concurrency... as of yet with no duplicates. I'll leave it running and see how it gets on.

**Comment by pacoorozco** [comment]
@mjhatcher, can you confirm that `issue-19` branch solves the album duplication?

**Comment by mjhatcher** [comment]
@pacoorozco, I can’t definitively say yes but it does look good.

It’s been uploading away, has done a few hundred photos across 20+ albums. Has stopped and been resumed a couple of times too. No duplicates yet.
